// actionengine/sound/soundfont/timgm6mb/SF2Index.js
// Auto-generated by split_soundfont.js
// Chainloads the TimGM6mb soundfont as 40 small chunk files instead of
// one multi-megabyte script, mirroring ActionModelPackageLoader's chainload pattern.
// Registers a manifest only - no chunk is fetched until SF2Loader.load("TimGM6mb").

(function () {
  const scriptUrl = document.currentScript ? document.currentScript.src : "";
  const baseDir = scriptUrl.substring(0, scriptUrl.lastIndexOf("/") + 1);

  const chunkPaths = [];
  for (let i = 0; i < 40; i++) {
    chunkPaths.push("chunks/chunk_" + String(i).padStart(3, "0") + ".js");
  }

  SF2Loader.registerPackage("TimGM6mb", chunkPaths, {
    dataUrlPrefix: "data:application/octet-stream;base64,"
  }, baseDir);
})();
